// // This file is generated by the FlutterFire CLI. Do not edit it manually.

// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'your-web-api-key',
//     authDomain: 'your-web-auth-domain',
//     projectId: 'your-project-id',
//     storageBucket: 'your-storage-bucket',
//     messagingSenderId: 'your-messaging-sender-id',
//     appId: 'your-web-app-id',
//     measurementId: 'your-measurement-id',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'your-android-api-key',
//     authDomain: 'your-android-auth-domain',
//     projectId: 'your-project-id',
//     storageBucket: 'your-storage-bucket',
//     messagingSenderId: 'your-messaging-sender-id',
//     appId: 'your-android-app-id',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'your-ios-api-key',
//     authDomain: 'your-ios-auth-domain',
//     projectId: 'your-project-id',
//     storageBucket: 'your-storage-bucket',
//     messagingSenderId: 'your-messaging-sender-id',
//     appId: 'your-ios-app-id',
//     iosClientId: 'your-ios-client-id',
//     iosBundleId: 'your-ios-bundle-id',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'your-macos-api-key',
//     authDomain: 'your-macos-auth-domain',
//     projectId: 'your-project-id',
//     storageBucket: 'your-storage-bucket',
//     messagingSenderId: 'your-messaging-sender-id',
//     appId: 'your-macos-app-id',
//     iosClientId: 'your-macos-client-id',
//     iosBundleId: 'your-macos-bundle-id',
//   );
// }
